from __future__ import annotations

from interview.followup.models import ExpectedEvidence, FollowUpStrategy


DEFAULT_FOLLOW_UP_STRATEGIES: tuple[FollowUpStrategy, ...] = (
    FollowUpStrategy(
        id="clarify_vague_reference",
        name="Clarify vague reference",
        category="clarification",
        methodology_ids=("funnel_probe",),
        applicable_stages=("early", "middle", "recovery"),
        applicable_evidence_categories=("context", "task", "action", "decision"),
        question_style_id="clarification",
        pressure_level=0,
        preferred_styles=("supportive", "standard", "formal"),
        question_shapes=("clarify_reference",),
        expected_evidence=(ExpectedEvidence("clear context or reference", "context"),),
        prompt_hints=("Ask what the vague phrase specifically refers to.",),
        disallowed_moves=("Do not evaluate the answer yet.",),
    ),
    FollowUpStrategy(
        id="personal_action_probe",
        name="Probe personal action",
        category="evidence_probe",
        methodology_ids=("star_behavioral",),
        applicable_stages=("early", "middle"),
        applicable_evidence_categories=("action", "collaboration", "decision"),
        question_style_id="evidence",
        pressure_level=0,
        preferred_styles=("supportive", "standard", "formal", "senior"),
        question_shapes=("ask_specific_action",),
        expected_evidence=(ExpectedEvidence("personal contribution", "action"),),
        prompt_hints=("Ask for the candidate's own concrete action, not the team's general work.",),
    ),
    FollowUpStrategy(
        id="metric_validation_probe",
        name="Validate result evidence",
        category="evidence_probe",
        methodology_ids=("star_behavioral",),
        applicable_stages=("middle", "late"),
        applicable_evidence_categories=("result", "metric"),
        question_style_id="evidence",
        pressure_level=0,
        preferred_styles=("standard", "formal", "senior"),
        question_shapes=("ask_metric",),
        expected_evidence=(ExpectedEvidence("metric, feedback, or before-after comparison", "metric"),),
        prompt_hints=("Ask for one verifiable result signal.",),
    ),
    FollowUpStrategy(
        id="tradeoff_depth_probe",
        name="Probe tradeoff and decision depth",
        category="depth_probe",
        methodology_ids=("funnel_probe",),
        applicable_stages=("middle", "late"),
        applicable_evidence_categories=("decision", "tradeoff", "business_judgment", "technical_depth"),
        question_style_id="evidence",
        pressure_level=1,
        preferred_styles=("formal", "senior", "final_round"),
        question_shapes=("ask_tradeoff",),
        expected_evidence=(ExpectedEvidence("tradeoff basis", "tradeoff"),),
        prompt_hints=("Ask why this option was chosen over a plausible alternative.",),
    ),
    FollowUpStrategy(
        id="attribution_challenge",
        name="Challenge attribution",
        category="pressure",
        methodology_ids=("bar_raiser_challenge",),
        applicable_stages=("middle", "late"),
        applicable_evidence_categories=("result", "metric", "business_judgment"),
        question_style_id="pressure",
        pressure_level=2,
        preferred_styles=("pressure", "senior", "final_round"),
        question_shapes=("challenge_attribution",),
        expected_evidence=(ExpectedEvidence("causal link between action and result", "result"),),
        prompt_hints=("Challenge the evidence link, not the candidate's character.",),
        disallowed_moves=("Do not accuse the candidate of exaggerating.",),
    ),
    FollowUpStrategy(
        id="reflection_redo_probe",
        name="Probe reflection and redo decision",
        category="reflection",
        methodology_ids=("reflection_learning",),
        applicable_stages=("late", "closing"),
        applicable_evidence_categories=("learning", "decision", "risk"),
        question_style_id="reflection",
        pressure_level=0,
        preferred_styles=("supportive", "standard", "senior", "final_round"),
        question_shapes=("ask_reflection",),
        expected_evidence=(ExpectedEvidence("lesson and changed future behavior", "learning"),),
        prompt_hints=("Ask what the candidate would change if doing it again.",),
    ),
    FollowUpStrategy(
        id="role_fit_connection_probe",
        name="Connect experience to role fit",
        category="role_fit",
        methodology_ids=("funnel_probe",),
        applicable_stages=("middle", "late", "closing"),
        applicable_evidence_categories=("role_fit", "business_judgment", "technical_depth"),
        question_style_id="evidence",
        pressure_level=0,
        preferred_styles=("standard", "formal", "final_round"),
        question_shapes=("connect_role",),
        expected_evidence=(ExpectedEvidence("explicit role-fit evidence", "role_fit"),),
        prompt_hints=("Ask how this experience proves fit for the target role.",),
    ),
    FollowUpStrategy(
        id="company_fit_connection_probe",
        name="Connect answer to company context",
        category="company_fit",
        methodology_ids=("funnel_probe",),
        applicable_stages=("opening", "middle", "late"),
        applicable_evidence_categories=("company_fit", "business_judgment"),
        question_style_id="company_fit",
        pressure_level=0,
        preferred_styles=("standard", "formal", "final_round"),
        question_shapes=("connect_company",),
        expected_evidence=(ExpectedEvidence("company understanding and motivation", "company_fit"),),
        prompt_hints=("Ask for preparation logic and role connection; do not assert unverified company facts.",),
    ),
    FollowUpStrategy(
        id="short_answer_recovery",
        name="Recover from short answer",
        category="recovery",
        methodology_ids=("funnel_probe",),
        applicable_stages=("early", "middle", "late", "recovery"),
        applicable_evidence_categories=("context", "action", "result"),
        question_style_id="relaxed",
        pressure_level=0,
        preferred_styles=("supportive", "standard"),
        question_shapes=("recover_narrow",),
        expected_evidence=(ExpectedEvidence("one concrete thing the candidate can confidently explain", "action"),),
        prompt_hints=("Narrow the question and reduce pressure.",),
        disallowed_moves=("Do not continue pressure probing after a very short answer.",),
    ),
)


def get_strategy(strategy_id: str) -> FollowUpStrategy | None:
    return next((strategy for strategy in DEFAULT_FOLLOW_UP_STRATEGIES if strategy.id == strategy_id), None)
